version: 0.0
os: linux
files:
  - source: index.html
    destination: /var/www/html/

hooks:
  ApplicationStop:
    - location: /script/restart_server
      timeout: 30
      runas: root
  BeforeInstall:
    - location: /script/before_install
      timeout: 30
      runas: root
  AfterInstall:
    - location: /script/restart_server
      timeout: 30
      runas: root